"""empty message

Revision ID: 0761049d292b
Revises: 18a8b9188750
Create Date: 2018-08-09 11:03:02.775623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0761049d292b'
down_revision = '18a8b9188750'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forward_primer', sa.Column('fw_primer_name', sa.String(length=10000), nullable=True))
    op.add_column('reverse_primer', sa.Column('rv_primer_name', sa.String(length=10000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reverse_primer', 'rv_primer_name')
    op.drop_column('forward_primer', 'fw_primer_name')
    # ### end Alembic commands ###
