"""empty message

Revision ID: 0a8768848c7e
Revises: 18ef1b71007d
Create Date: 2018-08-22 18:03:28.723022

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0a8768848c7e'
down_revision = '18ef1b71007d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('inferred_sequence_ibfk_2', 'inferred_sequence', type_='foreignkey')
    op.drop_column('inferred_sequence', 'submission_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inferred_sequence', sa.Column('submission_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('inferred_sequence_ibfk_2', 'inferred_sequence', 'submission', ['submission_id'], ['id'])
    # ### end Alembic commands ###
