"""empty message

Revision ID: 0aceaaa1b9b1
Revises: 32b8be9abf4a
Create Date: 2018-08-10 09:49:42.294370

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0aceaaa1b9b1'
down_revision = '32b8be9abf4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repertoire', sa.Column('primers_overlapping', sa.String(length=255), nullable=True))
    op.drop_column('repertoire', 'primers_not_overlapping')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repertoire', sa.Column('primers_not_overlapping', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('repertoire', 'primers_overlapping')
    # ### end Alembic commands ###
