"""empty message

Revision ID: 18ef1b71007d
Revises: a4f94b4d2e7f
Create Date: 2018-08-22 18:02:10.470212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18ef1b71007d'
down_revision = 'a4f94b4d2e7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inferred_sequence', sa.Column('submission_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'inferred_sequence', 'submission', ['submission_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inferred_sequence', type_='foreignkey')
    op.drop_column('inferred_sequence', 'submission_id')
    # ### end Alembic commands ###
