"""empty message

Revision ID: 21d280cdda94
Revises: 0aceaaa1b9b1
Create Date: 2018-08-11 13:22:01.827081

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '21d280cdda94'
down_revision = '0aceaaa1b9b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inference_tool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tool_name', sa.String(length=255), nullable=True),
    sa.Column('tool_version', sa.String(length=255), nullable=True),
    sa.Column('submission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submission.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('forward_primer', 'fw_primer_seq')
    op.drop_column('reverse_primer', 'rv_primer_seq')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reverse_primer', sa.Column('rv_primer_seq', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('forward_primer', sa.Column('fw_primer_seq', mysql.VARCHAR(length=255), nullable=True))
    op.drop_table('inference_tool')
    # ### end Alembic commands ###
