"""empty message

Revision ID: 32b8be9abf4a
Revises: dd15faa44bec
Create Date: 2018-08-10 09:35:30.776080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32b8be9abf4a'
down_revision = 'dd15faa44bec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repertoire', sa.Column('miarr_compliant', sa.String(length=255), nullable=True))
    op.add_column('repertoire', sa.Column('primers_not_overlapping', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repertoire', 'primers_not_overlapping')
    op.drop_column('repertoire', 'miarr_compliant')
    # ### end Alembic commands ###
