"""empty message

Revision ID: 399e04b65656
Revises: 81f497b438a6
Create Date: 2018-08-14 18:25:16.078792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '399e04b65656'
down_revision = '81f497b438a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forward_primer', sa.Column('fw_primer_name', sa.String(length=255), nullable=True))
    op.add_column('reverse_primer', sa.Column('rv_primer_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reverse_primer', 'rv_primer_name')
    op.drop_column('forward_primer', 'fw_primer_name')
    # ### end Alembic commands ###
