"""empty message

Revision ID: 4960130fc7f0
Revises: 8dc6a81665dd
Create Date: 2018-08-06 11:00:12.849343

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4960130fc7f0'
down_revision = '8dc6a81665dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pub_id', sa.Column('repertoire_id', sa.Integer(), nullable=True))
    op.drop_constraint('pub_id_ibfk_1', 'pub_id', type_='foreignkey')
    op.create_foreign_key(None, 'pub_id', 'repertoire', ['repertoire_id'], ['id'])
    op.drop_column('pub_id', 'repertoire')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pub_id', sa.Column('repertoire', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pub_id', type_='foreignkey')
    op.create_foreign_key('pub_id_ibfk_1', 'pub_id', 'repertoire', ['repertoire'], ['id'])
    op.drop_column('pub_id', 'repertoire_id')
    # ### end Alembic commands ###
