"""empty message

Revision ID: 4cfbadc065e7
Revises: 2c3e5a125ac0
Create Date: 2018-08-23 12:12:43.815015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cfbadc065e7'
down_revision = '2c3e5a125ac0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inferred_sequence', sa.Column('genotype_id', sa.Integer(), nullable=True))
    op.add_column('inferred_sequence', sa.Column('sequence_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'inferred_sequence', 'genotype', ['sequence_id'], ['id'])
    op.create_foreign_key(None, 'inferred_sequence', 'genotype_description', ['genotype_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inferred_sequence', type_='foreignkey')
    op.drop_constraint(None, 'inferred_sequence', type_='foreignkey')
    op.drop_column('inferred_sequence', 'sequence_id')
    op.drop_column('inferred_sequence', 'genotype_id')
    # ### end Alembic commands ###
