"""empty message

Revision ID: 4e70e7f082dd
Revises: f6cc7b35012f
Create Date: 2018-08-23 11:45:45.317867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e70e7f082dd'
down_revision = 'f6cc7b35012f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inferred_sequence', sa.Column('run_ids', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inferred_sequence', 'run_ids')
    # ### end Alembic commands ###
