"""empty message

Revision ID: 59001acee896
Revises: 763b46e1414b
Create Date: 2018-08-11 13:30:39.128247

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '59001acee896'
down_revision = '763b46e1414b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inference_tool', sa.Column('tool_starting_database', sa.Text(), nullable=True))
    op.drop_column('inference_tool', 'starting_database')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inference_tool', sa.Column('starting_database', mysql.TEXT(), nullable=True))
    op.drop_column('inference_tool', 'tool_starting_database')
    # ### end Alembic commands ###
