"""empty message

Revision ID: 75e2c5bb9072
Revises: 0761049d292b
Create Date: 2018-08-09 17:24:23.263382

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '75e2c5bb9072'
down_revision = '0761049d292b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acknowledgements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ack_name', sa.String(length=10000), nullable=True),
    sa.Column('ack_institution_name', sa.String(length=255), nullable=True),
    sa.Column('ack_ORCID_id', sa.String(length=255), nullable=True),
    sa.Column('submission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submission.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('repertoire', 'notes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repertoire', sa.Column('notes', mysql.VARCHAR(length=10000), nullable=True))
    op.drop_table('acknowledgements')
    # ### end Alembic commands ###
