"""empty message

Revision ID: 763b46e1414b
Revises: 21d280cdda94
Create Date: 2018-08-11 13:22:39.703061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '763b46e1414b'
down_revision = '21d280cdda94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forward_primer', sa.Column('fw_primer_seq', sa.String(length=1000), nullable=True))
    op.add_column('inference_tool', sa.Column('starting_database', sa.Text(), nullable=True))
    op.add_column('inference_tool', sa.Column('tool_settings', sa.Text(), nullable=True))
    op.add_column('reverse_primer', sa.Column('rv_primer_seq', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reverse_primer', 'rv_primer_seq')
    op.drop_column('inference_tool', 'tool_settings')
    op.drop_column('inference_tool', 'starting_database')
    op.drop_column('forward_primer', 'fw_primer_seq')
    # ### end Alembic commands ###
