"""empty message

Revision ID: 81f497b438a6
Revises: d46252593487
Create Date: 2018-08-14 18:24:54.923826

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '81f497b438a6'
down_revision = 'd46252593487'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forward_primer', 'fw_primer_name')
    op.drop_column('reverse_primer', 'rv_primer_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reverse_primer', sa.Column('rv_primer_name', mysql.VARCHAR(length=10000), nullable=True))
    op.add_column('forward_primer', sa.Column('fw_primer_name', mysql.VARCHAR(length=10000), nullable=True))
    # ### end Alembic commands ###
