"""empty message

Revision ID: 8a6805bd4b2c
Revises: 4f1be19eab44
Create Date: 2018-08-06 11:19:23.573482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a6805bd4b2c'
down_revision = '4f1be19eab44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forward_primer', sa.Column('repertoire_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'forward_primer', 'repertoire', ['repertoire_id'], ['id'])
    op.add_column('repertoire', sa.Column('submission_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'repertoire', 'repertoire', ['submission_id'], ['id'])
    op.add_column('reverse_primer', sa.Column('repertoire_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'reverse_primer', 'repertoire', ['repertoire_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reverse_primer', type_='foreignkey')
    op.drop_column('reverse_primer', 'repertoire_id')
    op.drop_constraint(None, 'repertoire', type_='foreignkey')
    op.drop_column('repertoire', 'submission_id')
    op.drop_constraint(None, 'forward_primer', type_='foreignkey')
    op.drop_column('forward_primer', 'repertoire_id')
    # ### end Alembic commands ###
