"""empty message

Revision ID: 8b1ca242b63a
Revises: 59001acee896
Create Date: 2018-08-11 13:37:04.019627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b1ca242b63a'
down_revision = '59001acee896'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inference_tool', sa.Column('settings_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inference_tool', 'settings_name')
    # ### end Alembic commands ###
