"""empty message

Revision ID: 8cc84b8cf0a0
Revises: 8b1ca242b63a
Create Date: 2018-08-11 13:40:12.957262

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8cc84b8cf0a0'
down_revision = '8b1ca242b63a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inference_tool', sa.Column('tool_settings_name', sa.String(length=255), nullable=True))
    op.drop_column('inference_tool', 'settings_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inference_tool', sa.Column('settings_name', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('inference_tool', 'tool_settings_name')
    # ### end Alembic commands ###
