"""empty message

Revision ID: 8dc6a81665dd
Revises: b051ff68ce54
Create Date: 2018-08-06 10:25:28.212664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dc6a81665dd'
down_revision = 'b051ff68ce54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repertoire',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_name', sa.String(length=255), nullable=True),
    sa.Column('repository_id', sa.String(length=255), nullable=True),
    sa.Column('dataset_url', sa.String(length=255), nullable=True),
    sa.Column('dataset_doi', sa.String(length=255), nullable=True),
    sa.Column('miarr_compliant', sa.Boolean(), nullable=True),
    sa.Column('miairr_link', sa.String(length=255), nullable=True),
    sa.Column('sequencing_platform', sa.String(length=255), nullable=True),
    sa.Column('read_length', sa.String(length=255), nullable=True),
    sa.Column('primers_not_overlapping', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.String(length=10000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('primer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('primer_seq', sa.String(length=255), nullable=True),
    sa.Column('repertoire', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repertoire'], ['repertoire.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pub_id',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pubmed_id', sa.Integer(), nullable=True),
    sa.Column('pub_title', sa.String(length=255), nullable=True),
    sa.Column('pub_authors', sa.String(length=255), nullable=True),
    sa.Column('repertoire', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repertoire'], ['repertoire.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pub_id')
    op.drop_table('primer')
    op.drop_table('repertoire')
    # ### end Alembic commands ###
