"""empty message

Revision ID: 92d719a97273
Revises: 8d45f7e7c1c3
Create Date: 2018-08-13 16:29:49.005240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92d719a97273'
down_revision = '8d45f7e7c1c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('acknowledgements', sa.Column('ack_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('acknowledgements', 'ack_name')
    # ### end Alembic commands ###
