"""empty message

Revision ID: a4f94b4d2e7f
Revises: c81a092de81a
Create Date: 2018-08-22 16:54:23.105722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4f94b4d2e7f'
down_revision = 'c81a092de81a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inferred_sequence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sequence_id', sa.String(length=255), nullable=True),
    sa.Column('genotype_id', sa.Integer(), nullable=True),
    sa.Column('repository_id', sa.String(length=255), nullable=True),
    sa.Column('deposited_version', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['genotype_id'], ['genotype_description.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inferred_sequence')
    # ### end Alembic commands ###
