"""empty message

Revision ID: b051ff68ce54
Revises: 4a1123acc197
Create Date: 2018-08-02 15:38:06.542397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b051ff68ce54'
down_revision = '4a1123acc197'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('committee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('committee', sa.String(length=80), nullable=True),
    sa.Column('species', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('committee'),
    sa.UniqueConstraint('species')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('committee')
    # ### end Alembic commands ###
