"""empty message

Revision ID: c81a092de81a
Revises: 399e04b65656
Create Date: 2018-08-21 16:20:49.166928

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c81a092de81a'
down_revision = '399e04b65656'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genotype_description', sa.Column('genotype_biosample_ids', sa.String(length=255), nullable=True))
    op.drop_column('repertoire', 'dataset_doi')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repertoire', sa.Column('dataset_doi', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('genotype_description', 'genotype_biosample_ids')
    # ### end Alembic commands ###
