"""empty message

Revision ID: d1031ecb8b48
Revises: e04e5dfc8be2
Create Date: 2018-08-13 16:21:47.597715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1031ecb8b48'
down_revision = 'e04e5dfc8be2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genotype_description',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genotyope_name', sa.String(length=255), nullable=True),
    sa.Column('genotype_subject_id', sa.String(length=255), nullable=True),
    sa.Column('genotype_filename', sa.String(length=255), nullable=True),
    sa.Column('genotype_file', sa.LargeBinary(), nullable=True),
    sa.Column('submission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submission.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('genotype', sa.Column('description_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'genotype', 'genotype_description', ['description_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'genotype', type_='foreignkey')
    op.drop_column('genotype', 'description_id')
    op.drop_table('genotype_description')
    # ### end Alembic commands ###
