"""empty message

Revision ID: f5a221feed22
Revises: 92d719a97273
Create Date: 2018-08-13 16:40:46.070443

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f5a221feed22'
down_revision = '92d719a97273'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genotype_description', sa.Column('genotype_name', sa.String(length=255), nullable=True))
    op.drop_column('genotype_description', 'genotyope_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genotype_description', sa.Column('genotyope_name', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('genotype_description', 'genotype_name')
    # ### end Alembic commands ###
