"""empty message

Revision ID: f6cc7b35012f
Revises: 0a8768848c7e
Create Date: 2018-08-22 18:05:32.306659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6cc7b35012f'
down_revision = '0a8768848c7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inferred_sequence', sa.Column('submission_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'inferred_sequence', 'submission', ['submission_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inferred_sequence', type_='foreignkey')
    op.drop_column('inferred_sequence', 'submission_id')
    # ### end Alembic commands ###
