
# ORM definitions for DupeGeneNote
# This file is automatically generated from the schema by schema/build_from_schema.py

from app import db
from db.userdb import User
from db.styled_table import *
from flask_table import Table, Col, LinkCol, create_table
from db.view_table import ViewCol
from sqlalchemy.orm import backref

class DupeGeneNote(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    date = db.Column(db.DateTime)
    author = db.Column(db.String(255))
    body = db.Column(db.Text())
    gene_description_id = db.Column(db.Integer, db.ForeignKey('gene_description.id'))
    gene_description = db.relationship('GeneDescription', backref = 'dupe_notes')
    genotype_id = db.Column(db.Integer, db.ForeignKey('genotype.id'))
    genotype = db.relationship('Genotype', backref = 'dupe_notes')


def save_DupeGeneNote(db, object, form, new=False):   
    object.body = form.body.data

    if new:
        db.session.add(object)
        
    db.session.commit()   



def populate_DupeGeneNote(db, object, form):   
    form.body.data = object.body




def copy_DupeGeneNote(c_from, c_to):   
    c_to.date = c_from.date
    c_to.author = c_from.author
    c_to.body = c_from.body



class DupeGeneNote_table(StyledTable):
    id = Col("id", show=False)
    date = StyledCol("date", tooltip="Date submission received")
    author = StyledCol("author", tooltip="email address of author")


def make_DupeGeneNote_table(results, private = False, classes=()):
    t = create_table(base=DupeGeneNote_table)
    ret = t(results, classes=classes)
    return ret

class DupeGeneNote_view(Table):
    item = ViewCol("", column_html_attrs={"class": "col-sm-3 text-right font-weight-bold view-table-row"})
    value = Col("")


def make_DupeGeneNote_view(sub, private = False):
    ret = DupeGeneNote_view([])
    ret.items.append({"item": "Note", "value": sub.body, "tooltip": "body text of entry", "field": "body"})
    return ret

