openapi: '3.1.0'

info:
  title: OGRDB API
  version: 2.0.0
  contact:
    name: AIRR Community
    url: 'http://ogrdb.airr-community.org/'
    email: join@airr-community.org
  description: >
    Major Version 2 of the Open Germline Receptor Database (OGRDB)
    web service application programming interface (API).
  license:
    name: European Union Public License version 1.2
    url: https://perma.cc/DK5U-NDVE

servers:
  - url: /api_v2
    description: OGRDB API
    variables:
      basePath:
        default: api_v2

components:
  schemas:
    #Service info object. This is the object returned by the /info request,
    #and provides information about the OGRDB API service and its attributes and capabilities
    service_info_object:
      description: Provides information about the OGRDB API service and it attributes and capabilities.
      allOf:
        - $ref: 'https://raw.githubusercontent.com/airr-community/airr-standards/release-1.5/specs/airr-schema-openapi3.yaml#/InfoObject'
        - type: object
          properties:
            api:
              $ref: 'https://raw.githubusercontent.com/airr-community/airr-standards/release-1.5/specs/airr-schema-openapi3.yaml#/InfoObject'
            schema:
              $ref: 'https://raw.githubusercontent.com/airr-community/airr-standards/release-1.5/specs/airr-schema-openapi3.yaml#/InfoObject'


    # The response object for species lists
    species_response:
      type: object
      properties:
        species:
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/airr-community/airr-standards/release-1.5/specs/airr-schema-openapi3.yaml#/Ontology'

    # The response object for germline set reference info
    GermlineSpeciesResponseItem:
      type: object
      properties:
        germline_set_id:
          type: string
        germline_set_name:
          type: string
        species:
          $ref: 'https://raw.githubusercontent.com/airr-community/airr-standards/release-1.5/specs/airr-schema-openapi3.yaml#/Ontology'
        species_subgroup:
          type: string
        species_subgroup_type:
          type: string
        locus:
          type: string

    # Schema for germline_species_response
    germline_species_response:
      type: object
      required:
        - germline_species
      properties:
        germline_species:
          type: array
          items:
            $ref: '#/components/schemas/GermlineSpeciesResponseItem'

    # list of germline sets
    germline_set_list:
      type: object
      required:
        - items
      properties:
        items:
          type: array
          items:
            $ref: './GermlineSet.yaml#/GermlineSet'

    # The response object for germline sets
    germline_set_response:
      type: object
      properties:
        Info:
          $ref: 'https://raw.githubusercontent.com/airr-community/airr-standards/release-1.5/specs/airr-schema-openapi3.yaml#/InfoObject'
        GermlineSet:
          $ref: '#/components/schemas/germline_set_list'
    
    # New schema for list of versions
    versions_response:
      type: object
      properties:
        versions:
          type: array
          items:
            type: number

    # error response
    error_response:
      type: object
      properties:
        message:
          type: string
          description: Detail about the error

paths:
  /:
    get:
      description: Service heartbeat.
      operationId: get_service_status
      responses:
        '200':
          description: Service is up.
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response'

  /info:
    get:
      description: Service information.
      operationId: get_info
      responses:
        '200':
          description: Success.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/service_info_object'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response'

  /germline/species:
    get:
      description: >
        Returns the species for which germline sets are available.
      operationId: get_species_api
      tags:
        - germline
      responses:
        '200':
          description: |
            A successful call returns the repertoire data.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/species_response'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response'

  /germline/sets/{species_id}:
    get:
      description: >
        Returns the reference information for available germline sets for a species.
      operationId: get_sets_api
      tags:
        - germline
      parameters:
        - name: species_id
          in: path
          description: ID of species
          required: true
          schema:
            type: string
      responses:
        '200':
          description: >
            A successful call returns the germline set reference information for the species.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/germline_species_response'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response'

  /germline/set/{germline_set_id}/{release_version}:
    get:
      description: >
        Returns a germline set based upon its identifier and version.
      operationId: get_versions_api
      tags:
        - germline
      parameters:
        - name: germline_set_id
          in: path
          description: ID of germline set to return
          required: true
          schema:
            type: string
        - name: release_version
          in: path
          description: Version of germline set to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: |
            A successful call returns the germline set data.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/germline_set_response'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response'

  /germline/set/{germline_set_id}/{release_version}/{format}:
    get:
      description: >
        Returns a germline set based upon its identifier and version.
      operationId: get_set_version_format_api
      tags:
        - germline
      parameters:
        - name: germline_set_id
          in: path
          description: ID of germline set to return
          required: true
          schema:
            type: string
        - name: release_version
          in: path
          description: Version of germline set to return
          required: true
          schema:
            type: string
        - name: format
          in: path
          description: format of germline set to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: |
            A successful call returns the germline set data in FASTA format.
          content:
            text/plain:
              schema:
                type: string
                format: binary
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response'


  /germline/set/{germline_set_id}/versions:
    get:
      description: >
        Returns a list of all versions of a germline set based on its identifier.
      operationId: list_all_versions_of_germline_set
      tags:
        - germline
      parameters:
        - name: germline_set_id
          in: path
          description: ID of germline set to return versions for
          required: true
          schema:
            type: string
      responses:
        '200':
          description: |
            A successful call returns the list of versions.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/versions_response'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response'

