
# FlaskForm class definitions for AttachedFile
# This file is automatically generated from the schema by schema/build_from_schema.py

from flask_wtf import FlaskForm
from flask_wtf.file import FileField
from custom_validators import *
from wtforms import StringField, SelectField, DateField, BooleanField, IntegerField, DecimalField, TextAreaField, HiddenField, validators, MultipleFileField
class AttachedFileForm(FlaskForm):
    filename = StringField('Attachment File Name', [validators.Length(max=255)], description="Filename as provided by user")


