
# FlaskForm class definitions for DupeGeneNote
# This file is automatically generated from the schema by schema/build_from_schema.py

from flask_wtf import FlaskForm
from flask_wtf.file import FileField
from custom_validators import *
from wtforms import StringField, SelectField, DateField, BooleanField, IntegerField, DecimalField, TextAreaField, HiddenField, validators, MultipleFileField
class DupeGeneNoteForm(FlaskForm):
    body = TextAreaField('Note', [validators.Length(max=10000), NonEmpty()], description="body text of entry")


