
# FlaskForm class definitions for GermlineSet
# This file is automatically generated from the schema by schema/build_from_schema.py

from flask_wtf import FlaskForm
from flask_wtf.file import FileField
from custom_validators import *
from wtforms import StringField, SelectField, DateField, BooleanField, IntegerField, DecimalField, TextAreaField, HiddenField, validators, MultipleFileField
class GermlineSetForm(FlaskForm):
    author = StringField('Author', [validators.Length(max=255), NonEmpty()], description="Corresponding author")
    lab_name = StringField('Lab Name', [validators.Length(max=255)], description="Department of corresponding author")
    lab_address = StringField('Lab Address', [validators.Length(max=255)], description="Institutional address of corresponding author")
    germline_set_name = StringField('Name', [validators.Length(max=255), NonEmpty()], description="descriptive name of this germline set")
    species = StringField('Species', [validators.Length(max=255), NonEmpty()], description="Binomial designation of subject's species")
    species_subgroup = StringField('Species subgroup', [validators.Length(max=255)], description="Race, strain or other species subgroup to which this subject belongs")
    species_subgroup_type = SelectField('Subgroup type', choices=[('none', 'none'), ('breed', 'breed'), ('strain', 'strain'), ('inbred', 'inbred'), ('outbred', 'outbred'), ('locational', 'locational')], description="Category of subgroup")
    locus = SelectField('Locus', choices=[('IGH', 'IGH'), ('IGK', 'IGK'), ('IGL', 'IGL'), ('TRA', 'TRA'), ('TRB', 'TRB'), ('TRG', 'TRG'), ('TRD', 'TRD')], description="Gene locus")
    release_description = StringField('Release Description', [validators.Length(max=255)])


