
# FlaskForm class definitions for NotesEntry
# This file is automatically generated from the schema by schema/build_from_schema.py

from flask_wtf import FlaskForm
from flask_wtf.file import FileField
from custom_validators import *
from wtforms import StringField, SelectField, DateField, BooleanField, IntegerField, DecimalField, TextAreaField, HiddenField, validators, MultipleFileField
class NotesEntryForm(FlaskForm):
    notes_text = TextAreaField('Notes', [validators.Length(max=10000)], description="Notes from submitter accompanying submission")
    notes_attachment = MultipleFileField('Attachments', description="File attachments from submitter accompanying submission")


