
# FlaskForm class definitions for NovelVdjbase
# This file is automatically generated from the schema by schema/build_from_schema.py

from flask_wtf import FlaskForm
from flask_wtf.file import FileField
from custom_validators import *
from wtforms import StringField, SelectField, DateField, BooleanField, IntegerField, DecimalField, TextAreaField, HiddenField, validators, MultipleFileField
class NovelVdjbaseForm(FlaskForm):
    vdjbase_name = StringField('Name', [validators.Length(max=255), NonEmpty()], description="Allele name (as recorded in VDJbase)")
    species = StringField('species', [validators.Length(max=255), NonEmpty()], description="Species")
    locus = SelectField('Locus', choices=[('IGH', 'IGH'), ('IGK', 'IGK'), ('IGL', 'IGL'), ('TRA', 'TRA'), ('TRB', 'TRB'), ('TRG', 'TRG'), ('TRD', 'TRD')], description="Gene locus")
    subject_count = IntegerField('Subjects', [], description="Number of subjects in which this allele is found")
    j_haplotypes = IntegerField('J-haplotypes', [], description="Number of samples in which this allele is J-haplotyped")
    d_haplotypes = IntegerField('D-haplotypes', [], description="Number of samples in which this allele is D-haplotyped")
    hetero_alleleic_j_haplotypes = IntegerField('hetero J-haplotypes', [], description="Number of samples in which this allele and at least one other allele of this gene are haplotyped")
    status = SelectField('Status', choices=[('not reviewed', 'not reviewed'), ('in review', 'in review'), ('rejected', 'rejected'), ('holding', 'holding'), ('submitted', 'submitted'), ('not current', 'not current'), ('modified', 'modified')], description="Review status")
    sequence = StringField('VDJbase sequence', [validators.Length(max=255)], description="Sequence in VDJbase")
    example = StringField('Example', [validators.Length(max=255)], description="Example sample in VDJbase displaying this allele")
    first_seen = DateField('First seen', description="Date VDJbase record was first seen")
    last_seen = DateField('Last seeen', description="Date VDJbase record was last seen")
    last_updated = DateField('Last updated', description="Date the comments or status were last updated")
    updated_by = StringField('Updated by', [validators.Length(max=255)], description="Name of last updater")


