
# FlaskForm class definitions for PrimerSet
# This file is automatically generated from the schema by schema/build_from_schema.py

from flask_wtf import FlaskForm
from flask_wtf.file import FileField
from custom_validators import *
from wtforms import StringField, SelectField, DateField, BooleanField, IntegerField, DecimalField, TextAreaField, HiddenField, validators
class PrimerSetForm(FlaskForm):
    primer_set_name = StringField('Primer Set Name', [validators.Length(max=255), NonEmpty()], description="Primer Set name or quick description")
    primer_set_notes = TextAreaField('Primer Set Notes', [validators.Length(max=10000)], description="Notes on Primer Set purpose/usage")


